### ISSUE TITLE
Some mandatory dependencies to add on README

### ISSUE THREAD

**Issue by tiago4171** [westscz/llameDL#2]
Hi,
First of all I have to congratulate you for nice initiative of this project. I hope that your project grows more and more.

I Was testing the program and I found some mandatory dependencies
They are:
ffmpeg
chromium-browser

Let me explain why. 
ffmpeg provides "ffprobe" and chromium-browser prevents this error:
```
tiago at Main-PC in ~/Music
↪ llamedl -u "https://www.youtube.com/watch?v=jFoMK49H0Oc"
Traceback (most recent call last):
  File "/usr/local/bin/llamedl", line 11, in <module>
    load_entry_point('LlameDL==0.1.0', 'console_scripts', 'llamedl')()
  File "/usr/local/lib/python3.6/dist-packages/LlameDL-0.1.0-py3.6.egg/llamedl/LLameDL.py", line 73, in main
    llamedl.main()
  File "/usr/local/lib/python3.6/dist-packages/LlameDL-0.1.0-py3.6.egg/llamedl/LLameDL.py", line 33, in main
    self.chrome = IChrome(bookmarks_path)
  File "/usr/local/lib/python3.6/dist-packages/LlameDL-0.1.0-py3.6.egg/llamedl/ichrome.py", line 22, in __init__
    self.bookmarks = bookmarks_path
  File "/usr/local/lib/python3.6/dist-packages/LlameDL-0.1.0-py3.6.egg/llamedl/ichrome.py", line 34, in bookmarks
    with open(bookmarks_path) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tiago/.config/chromium/Default/Bookmarks'
```
But it have some things to do. To generate the Bookmarks file we need to do a process. Follow this how to:
1. Install 'chromium-browser' on your Linux distribution
2. Open chromium-browser
3. Add a bookmark
With this, you'll generate the bookmark file

When I was typing this issue, I discovered something. If you do not want to include Chromium Browser as a dependency to your program on do that process above, just provide Bookmarks file at this location:

> $HOME/.config/chromium/Default/

and the program should work fine.
Here is an example of Bookmarks file:
```
{
   "checksum": "39915c79b7f2349447f0e3644fe5c26a",
   "roots": {
      "bookmark_bar": {
         "children": [  ],
         "date_added": "13170177110745130",
         "date_modified": "13170177111990968",
         "id": "1",
         "name": "Barra de favoritos",
         "type": "folder"
      },
      "other": {
         "children": [  ],
         "date_added": "13170177110745136",
         "date_modified": "0",
         "id": "2",
         "name": "Outros favoritos",
         "type": "folder"
      },
      "synced": {
         "children": [  ],
         "date_added": "13170177110745137",
         "date_modified": "0",
         "id": "3",
         "name": "Favoritos de dispositivos móveis",
         "type": "folder"
      }
   },
   "version": 1
}

```
Hope this helps. Thank you, and Keep Developing!!

**Comment by westscz** [comment]
Thanks for this words, this need to be fix as soon as possible! :)
